### ISSUE TITLE
extraction doesn't work

### ISSUE THREAD

**Issue by adoloman** [MadsAlbertsen/multi-metagenome#3]
files, needed for extraction of a positive ORFs, are not empty directories - such as list.of.positive.orfs.txt and assembly.orfs.faa. However, assembly.orfs.hmm.faa is empty, and during run, the execution message is:

> > 132 sequences to extract.
> > 11212 sequences in total.
> > 0 sequences extracted.

Is it an issue in code?

**Comment by MadsAlbertsen** [comment]
The code "should" work fine. The most common problem is a header structure that is not parsed correctly by the script.

If you send me an example of the input files I'll trace down the problem.

**Comment by adoloman** [comment]
Sent you an e-mail with input files

**Comment by MadsAlbertsen** [comment]
The problem is the header structure of your protein file (IIa.orfs.faa). Currently it is something like:
>scaffold-0_1 # 699 # 2027 # 1 # ID=1_1;partial=00;start_type=ATG;rbs_motif=AGGA;rbs_spacer=5-10bp;gc_cont=0.628

It needs to be simplified to:
>scaffold-0_1

In the shell script this is done by the following line: 

cut -f1 -d " " temp.orfs.faa > assembly.orfs.faa

In your case the following should work:

cut -f1 -d " " IIa.orfs.faa > assembly.orfs.faa
perl extract.using.header.list.pl -l list.of.positive.orfs.IIa.txt -s assembly.orfs.faa

**Comment by adoloman** [comment]
It worked.
Thank you so much!
